Root:
  RFSoC:
    Application:
      ########################################################
      ReadoutCtrl:
        EnableSoftTrig: True
      ########################################################
      DacSigGen:
        enable: True
        Enabled: 0x1
        Continuous: 0x1 # Continuous mode
        CsvFilePath: 'DacPatterns/16nsSpacingNoGap.csv'
      ########################################################
      PosCalc:
        ScratchPad: 0xBABECAFE
        AmpGainCorrect[:]: 1.0
        ####################
        xCoeff[0]: 0.0
        xCoeff[1]: +1.658E+01
        xCoeff[2]: 0.0
        xCoeff[3]: 0.0
        xCoeff[4]: 0.0
        xCoeff[5]: 0.0
        xCoeff[6]: 0.0
        xCoeff[7]: 0.0
        xCoeff[8]: 0.0
        xCoeff[9]: 0.0
        ####################
        yCoeff[0]: 0.0
        yCoeff[1]: 0.0
        yCoeff[2]: +1.658E+01
        yCoeff[3]: 0.0
        yCoeff[4]: 0.0
        yCoeff[5]: 0.0
        yCoeff[6]: 0.0
        yCoeff[7]: 0.0
        yCoeff[8]: 0.0
        yCoeff[9]: 0.0
        ####################
        SelectCross: Crossed
      ########################################################
