Root:
  RFSoC:
    Application:
      ########################################################
      ReadoutCtrl:
        EnableSoftTrig: True
      ########################################################
      DacSigGen:
        enable: True
        Enabled: 0x1
        Continuous: 0x1 # Continuous mode
        CsvFilePath: 'DacPatterns/16nsSpacingNoGap.csv'
      ########################################################
