Root:
  RFSoC:
    Application:
      ########################################################
      ReadoutCtrl:
        NcoFreqMHz: 1054.0
        EnableSoftTrig: True
      ########################################################
      DacSigGen:
        enable: True
        Enabled: 0x1
        Continuous: 0x1 # Continuous mode
        CsvFilePath: '4nsSpacingNoGap.csv'
        # CsvFilePath: '4nsSpacingGapAt16.csv'
      ########################################################
