Root:
  RFSoC:
    Application:
      ########################################################
      DacSigGen:
        enable: True
        Enabled: 0x1
        Continuous: 0x1 # Continuous mode
      ########################################################
      ReadoutCtrl:
        enable: True
        NcoFreqMHz: 1054.0
        DacDebugEnable: 1
        DacDebug[0]: 0
        DacDebug[1]: 0
        DacDebug[2]: 5000
        DacDebug[3]: 10000
        DacDebug[4]: 5000
        DacDebug[5]: 0
        DacDebug[6]: 0
        DacDebug[7]: 0
      ########################################################
