Root:
  RFSoC:
    Application:
      ########################################################
      AxiStreamRingBuffer:
        TrigBurst: 0x0
        ContinuousMode: 0x0 # Trigger mode
      ########################################################
      DacSigGen:
        enable: True
        Enabled: 0x1
        Continuous: 0x0 # Trigger mode
      ########################################################
