Root:
  RFSoC:
    Application:
      ########################################################
      DacSigGen:
        enable: True
        Enabled: 0x1
        Continuous: 0x1 # Continuous mode
      ########################################################
