Root:
  RFSoC:
    Application:
      ########################################################
      DacSigGen:
        enable: True
        Enabled: 0x1
        Continuous: 0x1 # Continuous mode
      ########################################################
      ReadoutCtrl:
        enable: True
        NcoFreqMHz: 1054.0
        DacDebugEnable: 1
        DacDebug[:]: 10000
        # DacDebug[0]: 0
        # DacDebug[1]: 0
        # DacDebug[2]: 0
        # DacDebug[3]: 0
        # DacDebug[4]: 0
        # DacDebug[5]: 0
        # DacDebug[6]: 0
        # DacDebug[7]: 0
      ########################################################
